---
- name: Configure hosts & deploy application
  gather_facts: no
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.132.0.53
  tasks:
    - name: Change MONGODB config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tag
      notify: Restart MONGODB
    - name: Add unit file for PUMA
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: Reload PUMA
    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/gryaznovart186/db_config
      tags: app-tag
    - name: Enable PUMA Service
      become: true
      systemd:
        name: puma
        enabled: yes
      tags: app-tag

  handlers:
    - name: Restart MONGODB
      become: true
      service:
        name: mongod
        state: restarted
    - name: Reload PUMA
      become: true
      systemd:
        name: puma
        state: restarted
